### ISSUE TITLE
[QUESTION]: Caching in the browser

### ISSUE THREAD

**Issue by kilievich-dmitriy-andreevich** [Danile71/go-rtsp#8]
Hello, I am writing a rtcp server and your library turned out to be very good and understandable. I launched your service following your example and as I understand it, the browser caches everything that I downloaded over the rtsp protocol. Is there any way to disable caching in the browser?

**Comment by Danile71** [comment]
You can add dynamic query parameter to request
stream?random=123456

**Comment by kilievich-dmitriy-andreevich** [comment]
> You can add dynamic query parameter to request stream?random=123456

Hello, sorry for the wait. I figured out what the problem was. The problem turned out not to be in your package, but in my nginx proxy, which cached everything that passes through it. Your package works very stable and well. Thank you for that!
